FROM public.ecr.aws/lambda/nodejs:20 AS builder

WORKDIR /usr/app

COPY package*.json ./
COPY tsconfig*.json nest-cli.json ./
RUN npm ci

COPY src ./src
COPY config ./config
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:20

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /usr/app/dist ./dist
COPY config ./config

CMD ["dist/src/lambda.handler.handler"]