version: '3.8'

services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    ports:
      - "9000:8080"
    environment:
      - AWS_REGION=ap-northeast-1
      - NODE_ENV=production
    volumes:
      - ./src:/var/task/src
      - ./config:/var/task/config